### ISSUE TITLE
How to use other scrape_configs than kube_sd_config

### ISSUE THREAD

**Issue by grobie** [coreos/kube-prometheus#10]
Instead of adding a short static configuration, the current setup creates a dummy service just so that all services get discovered via Kubernetes.

```yaml
- job_name: etcd
  static_configs:
  - targets: [172.17.4.51:2379]
```

This indirection seems to be just overhead. I assume it's the result of trying to completely generate prometheus.yml at some point. I think there should still be some way to provide non-kubernetes_sd_configs in that case.
