### ISSUE TITLE
[QUESTION] How to add new target

### ISSUE THREAD

**Issue by L3o-pold** [coreos/kube-prometheus#152]
I'd like to add a new target, I'm using a ServiceMonitor to do so.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: my-app
  name:  my-app
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: exporter
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      k8s-app:  my-app
```

There is no new target  in prometheus. 

How can I add my own service? 

For Grafana I only see a service, a service monitor and a service account. I was thinking that on my side I was supposed to add only a service monitor because my service is already up in the default namespace.
