### ISSUE TITLE
Prometheus adaptor fails to load custom metrics 

### ISSUE THREAD

**Issue by gogineni99** [coreos/kube-prometheus#160]
**What happened?**
Used a new rule in promethues adaptor-config ConfigMap to use a custom metric in HPA via CustomMetric API.Works fine when the metric used in 'seriesQuery' is valid. If the metric in 'serierQuery' is invalid (metric became invalid when the pods go down or the metric does not exist any longer), all other valid metrics/series fail to load.

```
E0722 15:00:58.683001       1 provider.go:206] unable to update list of all metrics: no metrics retrieved for query 
```

**Did you expect to see some different?**
Other than the rule/seriesQuery with invalid metric, the rest should load and should be available for custom metric API

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the manifest from https://github.com/coreos/kube-prometheus/blob/master/experimental/custom-metrics-api/custom-metrics-configmap.yaml
```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 
```
- Will give you results of custom metrics, which looks correct

Add a new rule with a invalid metric name like below. 

    ```
- seriesQuery: 'invalid_metric_name{namespace!="",pod!=""}'
      seriesFilters: []
      resources:
        overrides:
            namespace:
                resource: namespace
            pod:
                resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)' 
```     

```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 
```
- Will give you empty results.

**Environment**

* Prometheus Operator version: v0.31.0

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
    `kubectl version`
    

* Kubernetes cluster kind:
        Local minikube
    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: '{__name__=~"^container_.*",container_name!="POD",namespace!="",pod_name!=""}'
      seriesFilters: []
      resources:
        overrides:
          namespace:
            resource: namespace
          pod_name:
            resource: pod
      name:
        matches: ^container_(.*)_seconds_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}[1m])) by (<<.GroupBy>>)
    - seriesQuery: '{__name__=~"^container_.*",container_name!="POD",namespace!="",pod_name!=""}'
      seriesFilters:
      - isNot: ^container_.*_seconds_total$
      resources:
        overrides:
          namespace:
            resource: namespace
          pod_name:
            resource: pod
      name:
        matches: ^container_(.*)_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}[1m])) by (<<.GroupBy>>)
    - seriesQuery: '{__name__=~"^container_.*",container_name!="POD",namespace!="",pod_name!=""}'
      seriesFilters:
      - isNot: ^container_.*_total$
      resources:
        overrides:
          namespace:
            resource: namespace
          pod_name:
            resource: pod
      name:
        matches: ^container_(.*)$
        as: ""
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}) by (<<.GroupBy>>)
    - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
      seriesFilters:
      - isNot: .*_total$
      resources:
        template: <<.Resource>>
      name:
        matches: ""
        as: ""
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
    - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
      seriesFilters:
      - isNot: .*_seconds_total
      resources:
        template: <<.Resource>>
      name:
        matches: ^(.*)_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
    - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
      seriesFilters: []
      resources:
        template: <<.Resource>>
      name:
        matches: ^(.*)_seconds_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
    - seriesQuery: 'tomcat_requestcount_total{namespace!="",pod!=""}'
      seriesFilters: []
      resources:
        overrides:
            namespace:
                resource: namespace
            pod:
                resource: pod
      name:
        matches: ^(.*)_total
        as: "${1}_per_second"
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)
    - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
      seriesFilters: []
      resources:
        overrides:
            namespace:
                resource: namespace
            pod:
                resource: pod
      name:
        matches: ^(.*)_total
        as: "${1}_per_second"
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)
    - seriesQuery: 'invalid_metric_name{namespace!="",pod!=""}'
      seriesFilters: []
      resources:
        overrides:
            namespace:
                resource: namespace
            pod:
                resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'        
    resourceRules:
      cpu:
        containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
        nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[1m])) by (<<.GroupBy>>)
        resources:
          overrides:
            node:
              resource: node
            namespace:
              resource: namespace
            pod_name:
              resource: pod
        containerLabel: container_name
      memory:
        containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>}) by (<<.GroupBy>>)
        nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
        resources:
          overrides:
            node:
              resource: node
            namespace:
              resource: namespace
            pod_name:
              resource: pod
        containerLabel: container_name
      window: 1m

```

* Prometheus Adapter Logs:

```
E0722 15:39:50.045412       1 provider.go:206] unable to update list of all metrics: no metrics retrieved for query "invalid_metric_name{namespace!=\"\",pod!=\"\"}"
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:
