### ISSUE TITLE
nodeSelector ignored when detecting zone for PV creation. 

### ISSUE THREAD

**Issue by fgbreel** [coreos/kube-prometheus#173]
**What happened?**

Hello,

I found a quite interesting behavior yesterday while running prometheus on `masters` and having 1 `worker` node.

A cluster like this one:

```
NAME                                               STATUS   ROLES    ZONE     VERSION
ip-172-16-11-53.xx-region-1.compute.internal       Ready    master   113m     v1.15.1
ip-172-16-12-75.xx-region-1.compute.internal       Ready    master   3h12m    v1.15.1
ip-172-16-13-142.xx-region-1.compute.internal      Ready    node     3h50m    v1.15.1
ip-172-16-13-40.xx-region-1.compute.internal       Ready    master   91m      v1.15.1
```

and `kind: Prometheus` with:

```
  nodeSelector:
    beta.kubernetes.io/os: linux
    kubernetes.io/role: master
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  replicas: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - prometheus
        topologyKey: "kubernetes.io/hostname"
```

kube-controller finds only the zone where there is a `worker` node running:

```
I0729 16:49:52.523675       1 aws.go:1705] Found instances in zones map[xx-region-1c:{}]
```

then all 3 volumes are created in the 3rd zone, 2 masters keeps waiting,
rendering the cluster in this state:

```
NAME                                   READY   STATUS    RESTARTS   AGE     IP            NODE               NOMINATED NODE   READINESS GATES
prometheus-k8s-0                       0/3     Pending   0          83m     <none>        <none>             <none>           <none>
prometheus-k8s-1                       0/3     Pending   0          82m     <none>        <none>             <none>           <none>
prometheus-k8s-2                       3/3     Running   1          102m    10.244.10.4   ip-172-16-13-40    <none>           <none>
```

both pods cannot proceed due to these events:

```
Events:
  Type     Reason             Age                   From                Message
  ----     ------             ----                  ----                -------
  Normal   NotTriggerScaleUp  95s (x719 over 121m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't match node selector
  Warning  FailedScheduling   17s (x82 over 121m)   default-scheduler   0/4 nodes are available: 1 node(s) didn't match node selector, 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) had volume node affinity conflict.
```

**Environment**
1. `kube-prometheus` version `v0.30.0` and `v0.31.1`.
2. kubernetes `1.15.1` created with kops `1.14.0-alpha.3` running on top of debian stable.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a cluster with kops.
2. apply manifests with node selector and pod affinity.

Regards,
Gabriel Francisco
