### ISSUE TITLE
routePrefix  in Prometheus not work as Expected

### ISSUE THREAD

**Issue by dingsongjie** [coreos/kube-prometheus#174]
I have some config in Prometheus
```yaml
  baseImage: quay.io/prometheus/prometheus
  externalUrl: http://local.cluster-k8s.sample.cn
  routePrefix: /monitoring/prometheus
```
And I create a ingress-nginx use this
```yaml
  rules:
  - host: local.cluster-k8s.comteck.cn
    http:
      paths:
      - path: /monitoring/prometheus
        backend:
          serviceName: prometheus-k8s
          servicePort: 9090
```
But when I Access http://local.cluster-k8s.sample.cn/monitoring/prometheus ，It redirect to  http://local.cluster-k8s.sample.cn/graph  and there is a 404 error

Is my configuration wrong?

**Comment by brancz** [comment]
Have a look at the `rewrite-target` annotation in the ingress example here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/exposing-prometheus-and-alertmanager.md#ingress

That should solve the problem I believe.

**Comment by dingsongjie** [comment]
I use this
```yml
"annotations": {
      "kubernetes.io/ingress.class": "nginx",
      "nginx.ingress.kubernetes.io/rewrite-target": "/$1",
      "nginx.ingress.kubernetes.io/use-regex": "true"
    }
  },
  "spec": {
    "rules": [
      {
        "host": "local.cluster-k8s.comteck.cn",
        "http": {
          "paths": [
            {
              "path": "/prometheus/(.*)",
              "backend": {
                "serviceName": "prometheus-k8s",
                "servicePort": 9090
              }
            }
          ]
```
it works for me.
close it
