### ISSUE TITLE
prometheus-serviceMonitorKubelet doesn't apply

### ISSUE THREAD

**Issue by stafot** [coreos/kube-prometheus#192]
**What happened?**
 ```bash
kubectl apply -f kubernetes/resources/eks/staging/kube-prometheus/prometheus-serviceMonitorKubelet.yaml
The ServiceMonitor "kubelet" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"monitoring.coreos.com/v1", "kind":"ServiceMonitor", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"monitoring.coreos.com/v1\",\"kind\":\"ServiceMonitor\",\"metadata\":{\"annotations\":{},\"labels\":{\"k8s-app\":\"kubelet\"},\"name\":\"kubelet\",\"namespace\":\"monitoring\"},\"spec\":{\"endpoints\":[{\"bearerTokenFile\":\"/var/run/secrets/kubernetes.io/serviceaccount/token\",\"honorLabels\":true,\"interval\":\"30s\",\"port\":\"https-metrics\",\"scheme\":\"https\",\"tlsConfig\":{\"insecureSkipVerify\":true}},{\"bearerTokenFile\":\"/var/run/secrets/kubernetes.io/serviceaccount/token\",\"honorLabels\":true,\"interval\":\"30s\",\"metricRelabelings\":[{\"action\":\"drop\",\"regex\":\"container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)\",\"sourceLabels\":null},\"__name__\"],\"path\":\"/metrics/cadvisor\",\"port\":\"https-metrics\",\"scheme\":\"https\",\"tlsConfig\":{\"insecureSkipVerify\":true}}],\"jobLabel\":\"k8s-app\",\"namespaceSelector\":{\"matchNames\":[\"kube-system\"]},\"selector\":{\"matchLabels\":{\"k8s-app\":\"kubelet\"}}}}\n"}, "generation":1, "uid":"fe113676-c8ac-11e9-82aa-0a111a457804", "name":"kubelet", "namespace":"monitoring", "creationTimestamp":"2019-08-27T09:28:13Z", "labels":map[string]interface {}{"k8s-app":"kubelet"}}, "spec":map[string]interface {}{"namespaceSelector":map[string]interface {}{"matchNames":[]interface {}{"kube-system"}}, "selector":map[string]interface {}{"matchLabels":map[string]interface {}{"k8s-app":"kubelet"}}, "endpoints":[]interface {}{map[string]interface {}{"interval":"30s", "port":"https-metrics", "scheme":"https", "tlsConfig":map[string]interface {}{"insecureSkipVerify":true}, "bearerTokenFile":"/var/run/secrets/kubernetes.io/serviceaccount/token", "honorLabels":true}, map[string]interface {}{"tlsConfig":map[string]interface {}{"insecureSkipVerify":true}, "bearerTokenFile":"/var/run/secrets/kubernetes.io/serviceaccount/token", "honorLabels":true, "interval":"30s", "metricRelabelings":[]interface {}{map[string]interface {}{"action":"drop", "regex":"container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)", "sourceLabels":interface {}(nil)}, "__name__"}, "path":"/metrics/cadvisor", "port":"https-metrics", "scheme":"https"}}, "jobLabel":"k8s-app"}}: validation failure list:
spec.endpoints.metricRelabelings.sourceLabels in body must be of type array: "null"
spec.endpoints.metricRelabelings in body must be of type object: "string"
```
**Did you expect to see some different?**
`servicemonitor.monitoring.coreos.com/kubelet created`

****:
**How did you fixed it?**
Changed `0prometheus-operator-0servicemonitorCustomResourceDefinition`
from
```yaml
                        sourceLabels:
                          description: The source labels select values from existing
                            labels. Their content is concatenated using the configured
                            separator and matched against the configured regular expression
                            for the replace, keep, and drop actions.
                          items:
                            type: string
                          type: array
```
to 
```yaml
                        sourceLabels:
                          description: The source labels select values from existing
                            labels. Their content is concatenated using the configured
                            separator and matched against the configured regular expression
                            for the replace, keep, and drop actions.
                          items:
                            type: string
                            nullable: true
                          type: array
                          nullable: true
```
**Environment**
`AWS EKS worker. Amazon linux AMI`
* Prometheus Operator version:

    `Image:      quay.io/coreos/prometheus-operator:v0.31.1`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:

`AWS EKS`

* Manifests:

```
0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
prometheus-serviceMonitorKubelet.yaml
```

Is my fix a proper solution or am I missing something? Let me know to raise a relevant PR if so.
