### ISSUE TITLE
Replacing custom Prometheus config

### ISSUE THREAD

**Issue by brancz** [coreos/kube-prometheus#21]
I was thinking of what steps to take to get rid of the "custom" Prometheus config and have it make use of the means provided by the prometheus-operator.

Basically there is a bit of work left in bootkube regarding making all components self-hosted, but besides that I was trying to come up with a strategy on how to use Prometheus and prometheus-operator means to discover the kubernetes components. We will need to actively make sure that all kubernetes and tectonic components are properly labelled. As of right now the components are very well labelled with `k8s-app=<component-name>`.

If we want to utilize the `ServiceMonitor`s then we will need to create and maintain `Service` manifests for all kubernetes components - even those that don't actually need a `Service`. This is why I think we should get started with the `PodMonitor` (https://github.com/coreos/prometheus-operator/issues/38), it will allow us to discover all components without having to maintain those `Service` manifests because we can discover them based on `Pod`s having the `k8s-app` label, and have a section in the `PodMonitor` for a value to be used as the job label (same as the `ServiceMonitor`'s [`jobLabel`](https://github.com/coreos/prometheus-operator/blob/master/Documentation/service-monitor.md#servicemonitorspec)) and use the value of `k8s-app` for it.

Taking this a bit further, we should probably also start thinking of how we can have the Prometheus monitoring Kubernetes components only access the `kube-system` namespace, with what will hopefully result from https://github.com/prometheus/prometheus/issues/2280.

@fabxc @alexsomesan

**Comment by fabxc** [comment]
>  As of right now the components are very well labelled with k8s-app=<component-name>.

I recall one component being labeled with `k8s_app` instead. Is that fixed?

PodMonitor sounds like the right approach. At least for anything bootkube. But seems like we have to at least keep the manual one around as a template for any other setup.
Is there any news on the kubelet scraping issue where we can use our serviceaccount certs to scrape any kubelet but the one of the apiserver node? We are currently relabeling it to the (to be removed) read-only port.
I'd like to avoid enabling custom relabelings in our TPRs as long as possible.

We can already restrict namespaces from the operator side. With any changes to Prometheus, we would just make this generate a different configuration.

**Comment by brancz** [comment]
Did a quick check and found that you are right about that ... `kube-proxy` is the bad boy. Will address upstream.

**Comment by brancz** [comment]
For the record, upstream already [fixed](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/cluster/images/hyperkube/kube-proxy-ds.yaml) the label. But it is still to be done in [bootkube](https://github.com/kubernetes-incubator/bootkube/blob/ad7c0010c9c544187734fe9f28d0b89c136a0e94/pkg/asset/internal/templates.go#L263-L269). Will create a PR and update here.

**Comment by brancz** [comment]
FTR: https://github.com/kubernetes-incubator/bootkube/pull/230

**Comment by brancz** [comment]
Bootkube 0.2.6 was [released](https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.2.6) fixing the label and exposing kube-dns metrics. So we can try generating the config with `ServiceMonitor`s already or continue with the `PodMonitor` as both options should now work (although `ServiceMonitor`s will require `Service`/`Endpoints` objects to be created for discovery purposes).

**Comment by whereisaaron** [comment]
@brancz I was easily able to add Prometheus metrics and fairly easily able to add 'kube-dns' metrics (by creating a Service for the 'kube-dns' metrics port). So I can have node-exporter, kube-state-metrics, kube-dns, and Prometheus using the ServiceMonitor approach and without the custom config.

Where I think I am really stumped is I don't think I can watch the kubelet metrics, because I can't create a 'NodeMonitor' that results in a scrape config with `kubernetes_sd_configs: { "role": "node" }`. So while PodMonitor would be welcome, I can work around that with Services, whereas the lack of a NodeMonitor is a blocker. Or am I missing some trick/workaround?

If a NodeMonitor were added to Prometheus Operator then I think we could completely eliminate the "custom" config in kube-prometheus?

P.S. The [Prometheus k8s service discovery](https://github.com/prometheus/prometheus/blob/master/discovery/kubernetes/kubernetes.go#L149) supports 'nodes', 'services', 'pods', and 'endpoints'. It seems like 'ServiceMonitor' is really an 'EndpointsMonitor' (`kubernetes_sd_configs: { "role": "endpoints" }`)? With Service-specific labels (which create a [fairly brutal, all-namespaces watch of practically everything](https://github.com/prometheus/prometheus/blob/master/discovery/kubernetes/kubernetes.go#L154-L176)). If we had a PodMonitor, could ServiceMonitor could instead use `kubernetes_sd_configs: { "role": "service" }`?

```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
    env: live
spec:
  namespaceSelector:
    matchNames:
    - prometheus
  selector:
    matchLabels:
      app: prometheus
  endpoints:
  - port: web
    scheme: http
```

```
apiVersion: v1
kind: Service
metadata:
  name: kube-dns-metrics
  namespace: kube-system
  labels:
    metrics: kube-dns
    env: live
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 10055
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: kube-dns
```

```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: kube-dns
  namespace: prometheus
  labels:
    app: kube-dns
    env: live
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      metrics: kube-dns
  endpoints:
  - port: metrics
    scheme: http
```
