### ISSUE TITLE
Prometheus not getting pod information for CoreDNS or pods on AKS

### ISSUE THREAD

**Issue by mlbiam** [coreos/kube-prometheus#224]
**What did you do?**

Deployed per quickstart to AKS 

```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Did you expect to see some different?**

Expected to see pod metrics

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.32.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    AKS

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

It looks like it can scrape the api server because it gets the list of pods, just not the metrics for individual pods.  Also coredns doesn't seem to be reachable.

```
E0911 13:51:52.984237       1 reststorage.go:129] unable to fetch node metrics for node "aks-agentpool-14375870-0": no metrics known for node
E0911 13:51:53.095382       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/kube-proxy-zql2z, skipping
E0911 13:51:53.095410       1 provider.go:186] unable to fetch CPU metrics for pod kube-system/coredns-69b5b66fd8-h8898, skipping
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

Alerts- 

```
alert: TargetDown
expr: 100
  * (count by(job, namespace, service) (up == 0) / count by(job, namespace, service)
  (up)) > 10
for: 10m
labels:
  severity: warning
annotations:
  message: '{{ $value }}% of the {{ $labels.job }} targets are down.'
```

```
alert: Watchdog
expr: vector(1)
labels:
  severity: none
annotations:
  message: |
    This is an alert meant to ensure that the entire alerting pipeline is functional.
    This alert is always firing, therefore it should always be firing in Alertmanager
    and always fire against a receiver. There are integrations with various notification
    mechanisms that send a notification when this alert is not firing. For example the
    "DeadMansSnitch" integration in PagerDuty.
```

```
alert: CoreDNSDown
expr: absent(up{job="kube-dns"}
  == 1)
for: 15m
labels:
  severity: critical
annotations:
  message: CoreDNS has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-corednsdown
```

```
alert: KubeControllerManagerDown
expr: absent(up{job="kube-controller-manager"}
  == 1)
for: 15m
labels:
  severity: critical
annotations:
  message: KubeControllerManager has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
```

```
alert: KubeSchedulerDown
expr: absent(up{job="kube-scheduler"}
  == 1)
for: 15m
labels:
  severity: critical
annotations:
  message: KubeScheduler has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeschedulerdown
```

```
alert: KubeletDown
expr: absent(up{job="kubelet"}
  == 1)
for: 15m
labels:
  severity: critical
annotations:
  message: Kubelet has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletdown
```
