### ISSUE TITLE
Typo causes invalid manifest

### ISSUE THREAD

**Issue by pschulten** [coreos/kube-prometheus#236]
current version renders:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    relabelings:
    - action: replace
      regex: (.*)
      replacment: $1 # <--- should be 'replacement'
 ```

maybe here: https://github.com/coreos/kube-prometheus/commit/44dab893447ee73342932b22adb369cadb2c91dc#r35213716

and here: https://github.com/coreos/kube-prometheus/commit/aa7df507e98312f638c6a2aa7429906bc63949a6#r35213743
?
