### ISSUE TITLE
Prometheus operator baseImage from private repo not pulling

### ISSUE THREAD

**Issue by jeanluclariviere** [coreos/kube-prometheus#249]
**What did you do?**
I've been able to get all but the prometheus:v2.7.2 to pull down using a private repo and imagePullSecrets. 

**Did you expect to see some different?**
Yes, should have pulled the image from my private repo, instead of trying to download quay.io/prometheus/prometheus:v2.7.2

**Environment**

* Prometheus Operator version:

    `v2.7.2`

* Kubernetes version information:

    `1.14.6`

* Kubernetes cluster kind:

kubeadm.

* Manifests:

prometheus-prometheus.yaml

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: prometheus
              operator: In
              values:
              - k8s
          namespaces:
          - monitoring
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
      baseImage: example.com:8445/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  imagePullSecrets:
  - name: internal-registry-credentials
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.7.2
```

**Anything else we need to know?**:

updating the alertmanager-alertmanager.yaml file with the same configuration (updating the base image by adding my repo) allowed it to pull the image down without any issues.
