### ISSUE TITLE
Alerts no longer sending after upgrading from 1.14.8 to 1.15.5

### ISSUE THREAD

**Issue by jeanluclariviere** [coreos/kube-prometheus#291]
**What did you do?**
After upgraded from 1.14.8 to 1.15.5, alerts are no longer sending. The alerts are being triggered, I can see them in the alertmanager dashboard, but nothing is being sent. The same manifests applied to a cluster running 1.14.8 work just fine. Anyway suggestions on what steps I can take next to continue troubleshooting?

**Did you expect to see some different?**
Alerts should continue sending.

* Prometheus Operator version:

0.30

* Kubernetes version information:

1.15.8

* Kubernetes cluster kind:

kubeadm

* Manifests:
alertmanager.yaml (inside of the alertmanager)
```
global:
  resolve_timeout: 5m
route:
  receiver: 'email_alert'
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: 'null'
receivers:
- name: 'null'
- name: 'email_alert'
  email_configs:
  - send_resolved: true
    to: me@example.com
    smarthost: smtp.example.com:25
```

* Additional info:
I've specified these versions in my jsonnet as they were listed as kubernetes 1.15.x compatible.

```
    versions+:: {
      nodeExporter: "v0.18.1",
      kubeStateMetrics: "v1.7.2",
      }
```

edit: i realize i was incorrect, and updated my kube-state-metrics version from 1.6.0 to 1.7.2 to ensure compatibility 1.15.x as per their project https://github.com/kubernetes/kube-state-metrics. I'll monitor to see if this helps with the problem, though i don't think these two changes are related as the alerts are already firing.
