### ISSUE TITLE
Panel plugin not found: grafana-piechart-panel

### ISSUE THREAD

**Issue by johscheuer** [coreos/kube-prometheus#305]
**What happened?**

I did a fresh installation on a fresh Kubernetes cluster (1.15.5) and I get the following error in the `kubernetes-networking-cluster` dashboard:

```bash
Panel plugin not found: grafana-piechart-panel
```

It seems like the plugin is missing a simple `InitContainer` with the `grafana-cli plugins install grafana-piechart-panel` command solves this issue:

```yaml
      initContainers:
      - image: grafana/grafana:6.4.3
        name: grafana-init
        command:
        - bash
        - -c
        - grafana-cli plugins install grafana-piechart-panel
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
```

**Did you expect to see some different?**

I expected that Grafana has all required plugins :)

**How to reproduce it (as minimally and precisely as possible)**:

Just use the current master and apply the changes: 

```bash
ce5fe79 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #299 from coreos/fix-jb
```

**Environment**

Kubernetes with kubeadm

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    version: `quay.io/coreos/prometheus-operator:v0.34.0`

* Kubernetes version information:

    `kubectl version`

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    kubeadm (1.15.5)

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

The issue is pretty simple to fix I just don't know if the patch should be provided in this repository or somewhere else.
