### ISSUE TITLE
manifests created for wrong release

### ISSUE THREAD

**Issue by acidwars** [coreos/kube-prometheus#322]
**What happened?**

It seems to me that the manifests created are not in the correct version:

**Steps**
```
jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus
jb update
./build.sh oc-prom.jsonnet
```

* Manifests:

```jsonnet
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';  
local pvc = k.core.v1.persistentVolumeClaim;  
local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-bootkube.libsonnet') +
  (import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet')
  {
    _config+:: {
      namespace: 'monitoring',
    },

    prometheus+:: {
      namespaces: ["default", "kube-system","rook-ceph"],
      prometheus+: {
        spec+: {  
          retention: '14d',
          storage: {  
            volumeClaimTemplate:  
              pvc.new() +  
              pvc.mixin.spec.withAccessModes('ReadWriteOnce') +
              pvc.mixin.spec.resources.withRequests({ storage: '20Gi' }) +
              pvc.mixin.spec.withStorageClassName('rook-ceph-block'),

          },  // storage
        },  // spec
      },  // prometheus
    },  // prometheus

  };

{ ['setup/0namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{
  ['setup/prometheus-operator-' + name]: kp.prometheusOperator[name]
  for name in std.filter((function(name) name != 'serviceMonitor'), std.objectFields(kp.prometheusOperator))
} +
// serviceMonitor is separated so that it can be created after the CRDs are ready
{ 'prometheus-operator-serviceMonitor': kp.prometheusOperator.serviceMonitor } +
// { ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```
**Outcome**
For example the .yaml for the prometheus operator contains things like:
```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: prometheus-operator
    apps.kubernetes.io/version: v0.30.0
  name: prometheus-operator
  namespace: monitoring
```
Which seems to be for release 0.1
**Expected Outcome**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.34.0
  name: prometheus-operator
  namespace: monitoring
```

**Comment by acidwars** [comment]
Oh, I found the issue:
I was initially starting with release-0.1 which resulted in the following jsonnetfile.json:
```json
{
    "dependencies": [
        {
            "name": "kube-prometheus",
            "source": {
                "git": {
                    "remote": "https://github.com/coreos/kube-prometheus",
                    "subdir": "jsonnet/kube-prometheus"
                }
            },
            "version": "release-0.1"
        }
    ]
}
```
I changed the release, hit `jb update` and built again:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.33.0
  name: prometheus-operator
  namespace: monitoring
```
