### ISSUE TITLE
CustomResourceDefinition "prometheusrules.monitoring.coreos.com" is invalid

### ISSUE THREAD

**Issue by yogeek** [coreos/kube-prometheus#341]
**What happened?**

Sometimes, the following error appears when creating the CRDs :
```
kubectl apply -f kube-prometheus/manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The CustomResourceDefinition "prometheusrules.monitoring.coreos.com" is invalid: spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must not specify anything other than name and generateName, but metadata is implicitly specified
```

**Did you expect to see some different?**
```
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
```

**How to reproduce it (as minimally and precisely as possible)**:
It does not seem to be the case each time but I bumped into the error after several attempts of this command (sometimes the CRDS already existed, sometimes not) :
```
kubectl apply -f kube-prometheus/manifests/setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
```

**Environment**

* Prometheus Operator version:
v0.34.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

K8S cluster installed on AWS with kubeadm in HA mode

**Comment by yogeek** [comment]
_Maybe a hint_ :

In this [doc](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) it is noted that :

> 4. if metadata is specified, then only restrictions on metadata.name and metadata.generateName are allowed

In the CRD file, the metadata section contains neither `generateName` nor `name` by `type` :
```
validation:
    openAPIV3Schema:
      description: PrometheusRule defines alerting rules for a Prometheus instance
      properties:
        apiVersion:
          description: [...]
          type: string
        kind:
          description: [...]
          type: string
        metadata:
          type: object
```
