### ISSUE TITLE
How to add additional scrape configs

### ISSUE THREAD

**Issue by DimitrijeManic** [coreos/kube-prometheus#379]
Hey everyone, 

We have documentation on adding [additional-alert-rules](https://github.com/coreos/kube-prometheus/blob/master/examples/prometheus-additional-alert-rule-example.jsonnet) & [additional-recording-rules](https://github.com/coreos/kube-prometheus/blob/master/examples/prometheus-additional-recording-rule-example.jsonnet) but no documentation in regards to adding additional scrape configs. 

**How should additional scrape configs be added using kube-prometheus?** 
Do we need to create our own secret with the additional scrape configs and add them like this?
```JSONNET
    prometheus+:: {
      prometheus+: {
          spec+: {
              additionalScrapeConfigs : "secret_containing_additional_scrape_configs"
          }
      }
    },
```

If someone could guide me towards how this is done I could put up a PR for documentation.

**Comment by DimitrijeManic** [comment]
Hey @brancz 

I think my confusion is how that method is intended to be used with this jsonnet library?

I can create a simple .yaml and apply it with ```kubectl apply -f my-svc-monitor.yaml```
```YAML
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bonfire-apps
  labels:
    team: observability
spec:
  selector:
    matchLabels:
      app: my-pod
  endpoints:
    - port: metrics
      interval: "10s"
  targetLabels:
    - app
```

This creates the additional service scrape configuraiton I am looking for but I'm not sure how to tie it into this jsonnet library.
