### ISSUE TITLE
Adding AWS CNI ENI Metrics

### ISSUE THREAD

**Issue by rupadhya1** [coreos/kube-prometheus#402]
kube-prometheus was installed using the quick start.

We are using AWS VPC CNI in a non-EKS environment. 

kube-prometheus provides an example (examples/eks-cni-example.jsonnet)  and [EKS-cni-support page]( https://github.com/coreos/kube-prometheus/blob/master/docs/EKS-cni-support.md ) refers to the same.

The doc refers to prometheus-serviceMonitorAwsEksCNI.yaml.

I tried to use jsonnet to generate the new yaml but have been unsuccessful.
How do I generate the yaml file?

**Comment by rupadhya1** [comment]
Here are the instructions I used to compile the examples/eks-cni-example.jsonnet to monitor the AWS VPC CNI Metrics. 

Hope this helps. 

**Install go** 

```
wget https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
tar xvzf go1.13.7.linux-amd64.tar.gz 
sudo mv go /usr/local
export PATH=$PATH:/usr/local/go/bin:~/go/bin 
```

**Run go version to verify go is in the path** 

`go version `

> go version go1.13.7 linux/amd64


**Install the pre-requisites for compiling additional jsonnet files** 

```
go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
go get github.com/brancz/gojsontoyaml
go get github.com/google/go-jsonnet/cmd/jsonnet
```

**Get the kube-prometheus repo** 

```
git clone git@github.com:coreos/kube-prometheus.git
cd kube-prometheus 
jb install 
```
This will source the jsonnetfile.json and download the necessary dependencies and create the vendor dir


**Copy the eks-cni-example.jsonnet and compile it** 

```
cp examples/eks-cni-example.jsonnet .
./build.sh eks-cni-example.jsonnet 
```
This will delete and recreate all the manifests including the yamls for AWS CNI (Service, ServiceMonitor and the rules )


**Side Note:** There is an [issue with the latest build](https://github.com/coreos/kube-prometheus/issues/405#issuecomment-582710676) that is creating all the manifests in manifests directory and you may have to apply the manifests multiple times.

**Comment by rupadhya1** [comment]
Here are the yamls for adding the AWS VPC CNI Metrics:

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: aws-node
  name: aws-node
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: cni-metrics-port
    port: 61678
    targetPort: 61678
  selector:
    k8s-app: aws-node

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: eks-cni
  name: awsekscni
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: cni-metrics-port
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: aws-node


```
==============
**Prometheus-rules** 
```
  - name: kube-prometheus-eks.rules
    rules:
    - alert: EksAvailableIPs
      annotations:
        message: Instance {{ $labels.instance }} has less than 10 IPs available.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-eksavailableips
      expr: sum by(instance) (awscni_total_ip_addresses) - sum by(instance) (awscni_assigned_ip_addresses)
        < 10
      for: 10m
      labels:
        severity: critical

```
