### ISSUE TITLE
Prometheus not populating targets when it picks up service monitors.

### ISSUE THREAD

**Issue by evanrich** [coreos/kube-prometheus#473]
**What happened?**   Deploy servicemonitor, prometheus picks it up, but shows no target

**Did you expect to see some different?**   I expected it to work

**How to reproduce it (as minimally and precisely as possible)**:

Prometheus targets:
![image](https://user-images.githubusercontent.com/518320/77801259-bb873780-7035-11ea-9147-f82a6c635d93.png)

**Environment**

* Prometheus Operator version:

   quay.io/coreos/prometheus-operator:v0.38.0

* Kubernetes version information:

   1.17.4

* Kubernetes cluster kind:

    Created with Kubeadm

* Manifests:

ServiceMonitor
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: radarr4k
  namespace: media
  labels:
    app: radarr4k
spec:
  selector:
    matchLabels:
      app: radarr4k
  namespaceSelector:
    matchNames:
      - media
  endpoints:
  - port: exporter
    path: /metrics
    interval: 60s
    scheme: http
```

Exporter container in pod:
```
- name: radarr-exporter
        image: onedr0p/radarr-exporter:v1.0.1
        env:
        - name: radarr_apikey
          value: '<key>'
        - name: radarr_hostname
          value: 'http://127.0.0.1:7878'
        - name: interval
          value: '60s'
        ports:
          - name: exporter
            containerPort: 9811
```

Service:
```
apiVersion: v1
kind: Service
metadata:
  name: radarr4k
  namespace: media
spec:
  selector:
    app: radarr4k
  ports:
  - name: radarr4k
    port: 7878
    targetPort: 7878
  - name: exporter
    port: 9811
    targetPort: 9811
  type: LoadBalancer
```

* Prometheus Operator Logs:
NA

* Prometheus Logs:

NA (Doesn't show anything)

**Anything else we need to know?**:
I've tried following the following posts, but to no avail, also tried fully removing kube-prometheus and redoing it.. only the tautulli servicemonitor gets picked up

https://blog.pilosus.org/posts/2019/06/01/prometheus-operator-no-active-targets/

querying the metrics endpoint shows stats:
```
radarr_movie_quality_total{hostname="http://127.0.0.1:7878",quality=""} 18
radarr_movie_quality_total{hostname="http://127.0.0.1:7878",quality="Bluray-2160p"} 7
radarr_movie_quality_total{hostname="http://127.0.0.1:7878",quality="HDTV-2160p"} 1
radarr_movie_quality_total{hostname="http://127.0.0.1:7878",quality="Remux-2160p"} 219
radarr_movie_quality_total{hostname="http://127.0.0.1:7878",quality="WEBDL-2160p"} 4
radarr_movie_quality_total{hostname="http://127.0.0.1:7878",quality="WEBRip-2160p"} 3
# HELP radarr_movie_total Total number of movies
# TYPE radarr_movie_total gauge
radarr_movie_total{hostname="http://127.0.0.1:7878"} 252
# HELP radarr_queue_total Total number of movies in queue
# TYPE radarr_queue_total gauge
radarr_queue_total{hostname="http://127.0.0.1:7878"} 1
# HELP radarr_root_folder_space Root folder space
# TYPE radarr_root_folder_space gauge
radarr_root_folder_space{folder="/4k-movies/",hostname="http://127.0.0.1:7878"} 2.365769547776e+13
# HELP radarr_status System Status
# TYPE radarr_status gauge
radarr_status{hostname="http://127.0.0.1:7878"} 1
```
