### ISSUE TITLE
Prometheus rules: inconsistent rules attributes

### ISSUE THREAD

**Issue by mmallet-digipok** [coreos/kube-prometheus#583]
**What happened?**

We use the alertmanager to push alerts to our slack channels but we noticed that sometimes the content of the alerts was missing. We source the content from the alerts' `message` attribute but unfortunately, it seems that in `manifests/prometheus-rules.yaml` there are several (~27) alerts that have the `description` attribute instead of the `message` one.

**Did you expect to see some different?**

Yes. I would have expect to have all alerts formatted the same way, with either the message or the description attribute but not both. But as I am new to prometheus, I am certainly missing something here (like rules are supposed to have the same structure only within they group?). Thank you in advance for your help.

**How to reproduce it (as minimally and precisely as possible)**:

Extract from `manifests/prometheus-rules.yaml`:

An alert with the description attribute:
```yaml
   ...
    - alert: NodeFilesystemSpaceFillingUp
      annotations:
        description: Filesystem on {{ $labels.device }} at {{ $labels.instance }}
          has only {{ printf "%.2f" $value }}% available space left and is filling
          up.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemspacefillingup
        summary: Filesystem is predicted to run out of space within the next 24 hours.
   ...
```

An alert with the description attribute:
```yaml
   ...
  - name: kube-state-metrics
    rules:
    - alert: KubeStateMetricsListErrors
      annotations:
        message: kube-state-metrics is experiencing errors at an elevated rate in
          list operations. This is likely causing it to not be able to expose metrics
          about Kubernetes objects correctly or at all.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatemetricslisterrors
   ...
```

**Environment**

* Manifests:

   see https://github.com/coreos/kube-prometheus/blob/v0.5.0/manifests/prometheus-rules.yaml

Thank you!
