### ISSUE TITLE
Build is failed when namespace is present

### ISSUE THREAD

**Issue by vaclandic** [coreos/kube-prometheus#595]
**What happened?**
Hello, i am trying to build kubernetes-prometheus which includes prom-operator, alertmanager and prometheus
and i have next error:
```sh
Error: namespace transformation produces ID conflict: [{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"name":"prometheus-k8s","namespace":"monitoring"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s"},"subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"monitoring"}]}{nsfx:false,beh:unspecified} {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"name":"prometheus-k8s","namespace":"monitoring"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s"},"subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"monitoring"}]}{nsfx:false,beh:unspecified}]
```
 
**How to reproduce it (as minimally and precisely as possible)**:
It is take effect if in kustomization.yaml present namespace: monitoring
I know that in manifests from official repo namespace is present, but my kustomize manifests are depend on other kustomize manifests(in my example it is victoria-metrics) and in this manifests namespace is absent.

And other interesting thing, that in `../../../../victoria-metrics/single-server/base`  namespace: monitoring is present, but if i am delete namespace from kustomization.yaml in kube-prometheus and building it, i see that in resulting manifests for victoria-metrics namespace is default

**Environment**
* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.35.1

* Kubernetes version information:
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

* Manifests:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kustom-victoria-metrics-single-server
  path: patches/update-victoria-metrics-storage-resources.yaml

resources:
- namespace.yaml
- victoria-metrics-ingress.yaml
- grafana-ingress.yaml

bases:
- ../../base
- ../../../../victoria-metrics/single-server/base
- ../../../../kube-prometheus/prometheus-alertmanager/overlays/victoria-metrics
- ../../../../kube-prometheus/grafana/overlays/victoria-metrics-loki
```
